DROP VIEW IF EXISTS arlog;
create view arlog as
select
u.patient_name as patient_name,
u.date_of_birth as date_of_birth,
u.screening_or_clinical as screening_or_clinical,
u.district as district,
u.facility_of_origin as facility_of_origin,
u.state_lab_id as state_lab_id,
u.arln_accession_id as arln_accession_id,
u.sentinel_lab_id as sentinel_lab_id,
u.organism as organism,
u.mechanism_submitters_report as mechanism_submitters_report,
coalesce (
	nullif(pc."COLLECTION_DATE", 'NA')::date,
	nullif(u.date_of_collection, 'NA')::date
	)as date_of_collection,
u.source as source,
u.date_received as date_received,
u.date_reported as date_reported,
u.testing_lab as testing_lab,
coalesce(u.wgs_id, pc."WGS_ID") as wgs_id,
u.mlst_st as mlst_st,
u.blaimp_27 as blaimp_27,
u.blakpc_4 as blakpc_4,
coalesce(pc."BLANDM-1", u.blandm_1) as blandm_1,
coalesce(pc."BLANDM-5", u.blandm_5) as blandm_5,
coalesce(pc."BLAOXA-181_BLAOXA-48-LIKE", u.blaoxa_181_blaoxa_48_like) as blaoxa_181_blaoxa_48_like,
coalesce(pc."BLAOXA-1_BLAOXA-1-LIKE", u.blaoxa_1_blaoxa_1_like) as blaoxa_1_blaoxa_1_like
from (
select 
last_name || ', ' || first_name as patient_name,
date_of_birth,
'not in dataset' as screening_or_clinical,
'not in dataset' as district,
sample_collection_facility_if_included_on_ph_4182_form_ as facility_of_origin,
'not in dataset' as state_lab_id,
'not in dataset' as arln_accession_id,
'not in dataset' as sentinel_lab_id,
description_of_testing_completed_and_results_including_organism as organism,
'not in dataset' as mechanism_submitters_report,
date_of_collection_mm_dd_yyyy_ as date_of_collection,
specimen_source as source,
date_specimen_received as date_received,
date_reported,
submitting_facility as testing_lab,
'not in dataset' as wgs_id,
'not in dataset' as mlst_st,
999 as blaimp_27,
999 as blakpc_4,
999 as blandm_1,
999 as blandm_5,	
999 as blaoxa_181_blaoxa_48_like,
999 as blaoxa_1_blaoxa_1_like
from public.excel_cpo ec
union
select 
"LASTNAME" || ', ' || "FIRSTNAME" as 	patient_name,
"DATE_OF_BIRTH" as date_of_birth,
"SPECIMENTYPE" as screening_or_clinical,
'not in dataset' as district,
"HOSPFAC" as facility_of_origin,
"LAB" as state_lab_id,
"ACCESSION_NUM" as arln_accession_id,
'not in dataset' as sentinel_lab_id,
"DISEASE" as organism,
'not in dataset' as mechanism_submitters_report,
"COLLECTIONDT" as date_of_collection,
"SPECIMENSOURCE" as source,
'not in dataset' as date_received,
'not in dataset'date_reported,
"LAB" as testing_lab,
'not in dataset' as wgs_id,
'not in dataset' as mlst_st,
999 as blaimp_27,
999 as blakpc_4,
999 as blandm_1,
999 as blandm_5,	
999 as blaoxa_181_blaoxa_48_like,
999 as blaoxa_1_blaoxa_1_like
from public.excel_sent
union
select 
"PATIENT_NAME" as patient_name,
"DATE_OF_BIRTH" as date_of_birth,
'not in dataset' as screening_or_clinical,
'not in dataset' as district,
'not in dataset' as facility_of_origin,
"FACILITY" as state_lab_id,
"ACCESSION_NUM" as arln_accession_id,
'not in dataset' as sentinel_lab_id,
"RESULT" as organism,
'not in dataset' as mechanism_submitters_report,
"DATE_COLLECTED" as date_of_collection,
"SPECIMEN_TYPE" as source,
"DATE_RECEIVED" as date_received,
'not in dataset'as date_reported,
"FACILITY" as testing_lab,
'not in dataset' as wgs_id,
'not in dataset' as mlst_st,
999 as blaimp_27,
999 as blakpc_4,
999 as blandm_1,
999 as blandm_5,	
999 as blaoxa_181_blaoxa_48_like,
999 as blaoxa_1_blaoxa_1_like
from public.tenn_arln ta
union
select 
"PATIENT_NAME" as patient_name,
"PATIENT_DOB" as date_of_birth,
'not in dataset' as screening_or_clinical,
'not in dataset' as district,
'not in dataset' as facility_of_origin,
'not in dataset' as state_lab_id,
"LIMS_ACCESSION_ID" as arln_accession_id,
'not in dataset' as sentinel_lab_id,
'not in dataset' as organism,
'not in dataset' as mechanism_submitters_report,
"DATE_COLLECTED" as date_of_collection,
'not in dataset' as source,
"DATE_RECEIVED" as date_received,
'not in dataset'as date_reported,
"FACILITY_NAME" as testing_lab,
'not in dataset' as wgs_id,
'not in dataset' as mlst_st,
999 as blaimp_27,
999 as blakpc_4,
999 as blandm_1,
999 as blandm_5,	
999 as blaoxa_181_blaoxa_48_like,
999 as blaoxa_1_blaoxa_1_like
from public.web_portal wp
union 
select 
"PATIENT_NAME" as patient_name,
"DATE_OF_BIRTH" as date_of_birth,
'not in dataset' as screening_or_clinical,
'not in dataset' as district,
"RECEIVED_FROM" as facility_of_origin,
"LAB_ID" as state_lab_id,
"LAB_ID" as arln_accession_id,
'not in dataset' as sentinel_lab_id,
"ORGANISM_ID" as organism,
"CARBA_R_RESULT" as mechanism_submitters_report,
"DATE_OF_COLLECTION" as date_of_collection,
"SOURCE" as source,
'not in dataset' as date_received,
'not in dataset' as date_reported,
'not in dataset' as testing_lab,
'not in dataset' as wgs_id,
'not in dataset' as mlst_st,
999 as blaimp_27,
999 as blakpc_4,
999 as blandm_1,
999 as blandm_5,	
999 as blaoxa_181_blaoxa_48_like,
999 as blaoxa_1_blaoxa_1_like
from public.word_alert wa
) as u
left join public.pdf_cpo pc
	on u.arln_accession_id = pc."ACCESSION_ID"
	and NULLIF(u.date_of_collection, 'NA')::date = pc."COLLECTION_DATE"::date